version: '3.8'

services:
  frontend:
    container_name: election-poll-ui
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=https://api1.pietone.com
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - election-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  election-network:
    driver: bridge